name: cf_cli
description: Clean up the [build, ios/Pods] directory of Flutter projects in batches, optimize computer space
version: 1.3.0 #在 lib/cf.dart kCliVersion 设置版本
homepage: https://github.com/yy1300326388

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.0

executables:
  cf: main
