name: cf
description: 清理 Flutter 项目缓存，释放空间
version: 1.0.1 #在 lib/cf.dart kCliVersion 设置版本
homepage: https://github.com/yy1300326388

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.0
