name: cf_cli
description: 批量清理 Flutter 项目 [build、ios/Pods] 目录，优化电脑空间
version: 1.1.0 #在 lib/cf.dart kCliVersion 设置版本
homepage: https://github.com/yy1300326388

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.0

executables:
  cf: cf_cli
